global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASS}'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'email-notifications'
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'slack-notifications'
      repeat_interval: 3h

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: '${NOTIFICATION_EMAIL}'
        send_resolved: true
        html: '{{ template "email.custom.html" . }}'
        headers:
          subject: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'

  - name: 'slack-notifications'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#monitoring'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'

templates:
  - '/etc/alertmanager/template/*.tmpl'
